### ISSUE TITLE
Should add module using `load` to the `CoreLoadPlugin` map when imported in tests

### ISSUE THREAD

**Issue by agubler** [dojo/cli-build#106]
**Bug** 

Currently if we build (with no auto bundling) a project that uses `load(require, './MyWidget')` and the module is imported in unit tests, the tests fail for `Missing module: src/MyWidget`.

Expected behaviour is to ensure that modules are added to the map in `CoreLoadPlugin` if they are imported in the unit tests even if the `load` is registered in the projects `src` directory.

**Comment by mwistrand** [comment]
As far as I can tell, this isn't just a problem with running `dojo test`; the widget is not added to the `__modules__` map with `dojo build` either.

**Comment by mwistrand** [comment]
`cli-build` is working as intended: mids are parsed from `@dojo/core/load` calls if 1) the `disableLazyWidgetDetection` is falsy and 2) the `load` call is coming from within a `WidgetRegistry#define`.

`@dojo/cli-test-intern` sets `disableLazyWidgetDetection` to `true` without a means of changing that. I've opened a [new issue](https://github.com/dojo/cli-test-intern/issues/36) in that repo.
