### ISSUE TITLE
npm has different name

### ISSUE THREAD

**Issue by sebilasse** [dojo/cli-build#130]
This package is named

`@dojo/cli-build-webpack` on npm

but the Documentation / Readme says
`npm install @dojo/cli-build` (which does not work)

Could you name it `@dojo/cli-build` on npm ?

**Comment by agubler** [comment]
Thank you for pointing this out, I have raised a PR to updated the readme [here](https://github.com/dojo/cli-build/pull/134).

The repository should really be named, `cli-build-webpack` rather than renaming the package to `cli-build`.
