### ISSUE TITLE
Passing extra commands to webpack

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli-build#21]
Would it be possible to find a way to pass additional arguments to `webpack`?  In particular it might be handy to be able to pass the `--json` argument to be able to generate `webpack` stats for analysis.  With the zero configuration nature of the CLI it become challenging to figure out how to get `webpack` to run standalone.

**Comment by matt-gadd** [comment]
No. We will be offering the build visualisations that I have shown on a production build though built in. Please see https://github.com/dojo/cli/issues/44 for ejecting config for advanced users.
