### ISSUE TITLE
Improve documentation (webpack config and readme)

### ISSUE THREAD

**Issue by dylans** [dojo/cli-build#34]
Document how to configure webpack for builds. Should probably add a better README file as well.

**Comment by agubler** [comment]
The intention is that users cannot configure webpack for builds whilst using the CLI but would need to `eject` in order to get access to the configuration files and but would be out of the dojo cli build eco system.

The readme perhaps should be updated to reflect this.

**Comment by rishson** [comment]
@dylans @agubler I think we're OK to close this now, as we have documented `eject` in the README for `cli-build`. Please re-open if you think further work is required here.
