### ISSUE TITLE
"Error: EMFILE: too many open files" on Windows while running build on large project

### ISSUE THREAD

**Issue by RoyTinker** [dojo/cli-build#35]
It looks like the solution is to monkey-patch `fs` using graceful-fs inside the webpack.config.js file: https://github.com/kevlened/copy-webpack-plugin/issues/59#issuecomment-228563990

EDIT: tried that, didn't work. Looks like other solutions are proposed further down the thread.

EDIT 2: updating dojo-cli-build-webpack to use copy-webpack-plugin v4.0.1 seems to have solved the problem.

**Comment by matt-gadd** [comment]
@RoyTinker thanks for raising the issue! does updating `copy-webpack-plugin` still require the monkey patch, or does that fix it in itself?

**Comment by RoyTinker** [comment]
@matt-gadd Looks like the monkey patch is not required in that case.

**Comment by matt-gadd** [comment]
@RoyTinker awesome, i've raised a PR to update the plugin. thanks!

**Comment by RoyTinker** [comment]
@matt-gadd No problem, happy new year!

**Comment by omerts** [comment]
@RoyTinker  Using v4.0.1, we are still having the issue in our system, where we copy many svg files to our output directory. 
Using webpack version: 2.1.0-beta.20
Node: v6.3.1
