### ISSUE TITLE
Only TypeScript-specific UMD wrappers are ignored

### ISSUE THREAD

**Issue by mwistrand** [dojo/cli-build#41]
**Bug**

`dojo/cli-build` uses a loader that forces the AMD portion of UMD wrappers to be skipped, but it is specific to the UMD wrappers generated by TypeScript (specifically by searching for the presence of `var v = factory(require, exports); if (v !== undefined) module.exports = v;`. As such, the build still chokes on UMD modules with different wrappers.

Package Version: All versions, including alpha.6

**Code**

```javascript
// The following UMD wrapper is correctly bypassed
(function (dependencies, factory) {
    if (typeof module === 'object' && typeof module.exports === 'object') {
        var v = factory(require, exports); if (v !== undefined) module.exports = v;
    }
    else if (typeof define === 'function' && define.amd) {
        define(dependencies, factory);
    }
})(["require", "exports"], function (require, exports) {});

// The following UMD wrapper is not bypassed
(function(global, factory) {
	if ( typeof define === 'function' && define.amd ) {
		define([], factory);
	} else if ( typeof exports === 'object') {
		module.exports = factory();
	}
}( this, function() {});
```

**Comment by mwistrand** [comment]
Admittedly I'm more familiar with plugins than loaders, but I wonder if a plugin would be required to handle this.

**Comment by dylans** [comment]
There really are two different types of UMD, one which allows falling back to a global object and one that does not.

**Comment by mwistrand** [comment]
I've updated the example in the description since the issue is not that the version that falls back to a global is not recognized, but rather that the test used to detect UMD modules is very specific to TypeScript modules.

**Comment by matt-gadd** [comment]
As discussed before this should be easily solvable using the imports-loader no? The reason the umd loader is specific to TypeScripts umd format, is the TypeScript umd wrapper is not bypassable using the imports-loader.

**Comment by matt-gadd** [comment]
Also the umd compareloader doesn't bypass as such (which is what imports-loader does ), it effectively rewrites the module to commonjs (or amd) removing the wrapper completely.

**Comment by matt-gadd** [comment]
If this `umd` wrapper does fail when using the `imports-loader` I can add it to the loader. It doesn't look like it should though.

**Comment by mwistrand** [comment]
@matt-gadd I had completely forgotten that we'd already discussed this. You are correct that `imports-loader` works in this scenario. Apologies!
