### ISSUE TITLE
Currently needs git as a pre-req due to reliance on non-published module

### ISSUE THREAD

**Issue by rishson** [dojo/cli-build#76]
Can we either publish `"source-map-loader": "bryanforbes/source-map-loader#463701b",` or remove the dep for something else please?

At the moment, you cannot use the cli to bootstrap a project unless you have `git` installed and relying on non-publically-versioned things is not great.

**Comment by dylans** [comment]
Is source-map-loader something specific for Dojo 2 or a fork of another project?

**Comment by rishson** [comment]
@bryanforbes ?

**Comment by kitsonk** [comment]
In fact the commit that it is depending upon has been blatted from the @bryanforbes fork, so you can no longer install this package. 😭

**Comment by rishson** [comment]
..which is a perfect example of why non-published deps being bad.

**Comment by rishson** [comment]
I'd like this done for beta 1 because relying on a non npm dep is more error prone that I would like. I don't care if the dep is published under Dojo or not, just that it is published (so can be resurrected if the repo goes away, or the commit, or..)
